schelete loader
mesterum/parcel-team6-JS pull request #12
Opened 2024-03-06 14:43 UTC by Andree-Ioana

2024-03-07 10:19 UTC, mesterum commented
Ideea e bună dar mă gândeam să fie 20 de placeholdere de dimensiunea posterelor, din alea gri, care să stea pînă vin imaginile și titlurile reale. O librărie pe undeva?

2024-03-08 21:30 UTC, exigibil approved these changes

2024-03-08 21:31 UTC, exigibil requested changes
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
src/sass/index.scss

2024-03-09 10:36 UTC, czke33 approved these changes

2024-03-10 08:08 UTC, closed without merging